// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesisPractica.Models;

#nullable disable

namespace TesisPractica.Migrations
{
    [DbContext(typeof(TesisDbContext))]
    partial class TesisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTarea")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdComentario");

                    b.HasIndex("IdTarea");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("Pieza", b =>
                {
                    b.Property<int>("IdPieza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPieza"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("IdPieza");

                    b.HasIndex("IdCliente");

                    b.ToTable("Piezas", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Analisis5Porque", b =>
                {
                    b.Property<int>("IdAnalisis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnalisis"));

                    b.Property<string>("CuartoPorque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCausa")
                        .HasColumnType("int");

                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<string>("PrimerPorque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuintoPorque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoPorque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TercerPorque")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnalisis");

                    b.HasIndex("IdFichaTecnica", "IdCausa")
                        .IsUnique();

                    b.ToTable("Analisis5Porque");
                });

            modelBuilder.Entity("TesisPractica.Models.Categoria5M", b =>
                {
                    b.Property<int>("IdCategoria5M")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCategoria5M");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria5M"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descripcion");

                    b.HasKey("IdCategoria5M");

                    b.ToTable("Categorias5M", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Causa", b =>
                {
                    b.Property<int>("IdCausa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCausa"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCausa");

                    b.ToTable("Causa", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.CausaPaso", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdCausa")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<short?>("ClasificacionImpacto")
                        .HasColumnType("smallint");

                    b.Property<string>("DescripcionCausa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short?>("EsCausaRaiz")
                        .HasColumnType("smallint");

                    b.Property<int>("IdCategoria5M")
                        .HasColumnType("int");

                    b.Property<short?>("ResultadoVerificacion")
                        .HasColumnType("smallint");

                    b.HasKey("IdFichaTecnica", "IdCausa");

                    b.HasIndex("IdCategoria5M");

                    b.ToTable("CausasPasos", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Causa_NC", b =>
                {
                    b.Property<int>("IdCausa")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("IdNoConformidad")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("IdCausa", "IdNoConformidad");

                    b.HasIndex("IdNoConformidad");

                    b.ToTable("Causa_NC", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.CorridaProduccion", b =>
                {
                    b.Property<int>("IdProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduccion"));

                    b.Property<int>("CantidadNoOK")
                        .HasColumnType("int");

                    b.Property<int>("CantidadOK")
                        .HasColumnType("int");

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProduccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.HasKey("IdProduccion");

                    b.HasIndex("IdFichaTecnica")
                        .IsUnique();

                    b.ToTable("CorridaProduccion", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Defecto", b =>
                {
                    b.Property<int>("IdDefecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDefecto"));

                    b.Property<string>("NombreDefecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDefecto");

                    b.ToTable("Defectos", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Defecto_NC", b =>
                {
                    b.Property<int>("IdDefecto")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("IdNoConformidad")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("IdDefecto", "IdNoConformidad");

                    b.HasIndex("IdNoConformidad");

                    b.ToTable("Defectos_NC", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Detectabilidad", b =>
                {
                    b.Property<int>("IdDetectabilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetectabilidad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDetectabilidad");

                    b.ToTable("Detectabilidad");
                });

            modelBuilder.Entity("TesisPractica.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCreador")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEquipo");

                    b.HasIndex("IdCreador");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Equipos_Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<string>("RolEnEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario", "IdEquipo");

                    b.HasIndex("IdEquipo");

                    b.ToTable("Equipos_Usuarios", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.FichaTecnica", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFichaTecnica"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdNoConformidad")
                        .HasColumnType("int");

                    b.HasKey("IdFichaTecnica");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdNoConformidad")
                        .IsUnique();

                    b.ToTable("FichaTecnica", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.NoConformidad", b =>
                {
                    b.Property<int>("IdNoConformidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNoConformidad"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Consecuencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIncidente")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProduccion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Frecuencia")
                        .HasColumnType("int");

                    b.Property<string>("Gravedad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDetectabilidad")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPieza")
                        .HasColumnType("int");

                    b.Property<int>("IdPrioridad")
                        .HasColumnType("int");

                    b.Property<int>("IdProceso")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Recurrencia")
                        .HasColumnType("bit");

                    b.HasKey("IdNoConformidad");

                    b.HasIndex("IdDetectabilidad");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPieza");

                    b.HasIndex("IdPrioridad");

                    b.HasIndex("IdProceso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("NoConformidad", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Paso0Contencion", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<string>("AccionContencion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Almacen_CantControlada")
                        .HasColumnType("int");

                    b.Property<int?>("Almacen_CantOk")
                        .HasColumnType("int");

                    b.Property<int?>("Almacen_CantSospechosa")
                        .HasColumnType("int");

                    b.Property<int?>("BordeLinea_CantControlada")
                        .HasColumnType("int");

                    b.Property<int?>("BordeLinea_CantOk")
                        .HasColumnType("int");

                    b.Property<int?>("BordeLinea_CantSospechosa")
                        .HasColumnType("int");

                    b.Property<int?>("Deposito_CantControlada")
                        .HasColumnType("int");

                    b.Property<int?>("Deposito_CantOk")
                        .HasColumnType("int");

                    b.Property<int?>("Deposito_CantSospechosa")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("MetodoControl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Responsable")
                        .HasColumnType("int");

                    b.HasKey("IdFichaTecnica");

                    b.HasIndex("IdEstado");

                    b.HasIndex("Responsable");

                    b.ToTable("Paso0_Contencion", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Paso1Verificacion", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<string>("ComoSucede")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CualPieza")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CuandoSucede")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdOperador")
                        .HasColumnType("int");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QueSucede")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuienDetecta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Responsable")
                        .HasColumnType("int");

                    b.Property<short?>("TipoProblema")
                        .HasColumnType("smallint");

                    b.Property<short?>("Turno")
                        .HasColumnType("smallint");

                    b.HasKey("IdFichaTecnica");

                    b.ToTable("Paso1", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Paso2AnalisisCausa", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("Responsable")
                        .HasColumnType("int");

                    b.HasKey("IdFichaTecnica");

                    b.ToTable("Paso2", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Paso3", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("Responsable")
                        .HasColumnType("int");

                    b.HasKey("IdFichaTecnica");

                    b.ToTable("Paso3", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Paso4", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("Responsable")
                        .HasColumnType("int");

                    b.HasKey("IdFichaTecnica");

                    b.ToTable("Paso4", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Paso5", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<short?>("Defectos")
                        .HasColumnType("smallint");

                    b.Property<short?>("EstandarCalidad")
                        .HasColumnType("smallint");

                    b.Property<short?>("FacilidadSeguimiento")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<short?>("Instrucciones")
                        .HasColumnType("smallint");

                    b.Property<short?>("LiberacionDefectos")
                        .HasColumnType("smallint");

                    b.Property<short?>("ParametrosCeroDefectos")
                        .HasColumnType("smallint");

                    b.Property<int>("Responsable")
                        .HasColumnType("int");

                    b.Property<short?>("Variacion")
                        .HasColumnType("smallint");

                    b.Property<short?>("VariacionTrabajo")
                        .HasColumnType("smallint");

                    b.HasKey("IdFichaTecnica");

                    b.ToTable("Paso5", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Paso6", b =>
                {
                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("Responsable")
                        .HasColumnType("int");

                    b.HasKey("IdFichaTecnica");

                    b.ToTable("Paso6", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Prioridad", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrioridad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPrioridad");

                    b.ToTable("Prioridad", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Proceso", b =>
                {
                    b.Property<int>("IdProcesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProcesos"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProcesos");

                    b.ToTable("Procesos", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("AccionDeMejora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanalImplementacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionDeMejora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaObjetivo")
                        .HasColumnType("date");

                    b.Property<int>("IdCausaPasos")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdFichaTecnica")
                        .HasColumnType("int");

                    b.Property<int>("IdPrioridad")
                        .HasColumnType("int");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoAccion")
                        .HasColumnType("int");

                    b.Property<string>("LugarAplicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTarea");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPrioridad");

                    b.HasIndex("IdResponsable");

                    b.HasIndex("IdTipoAccion");

                    b.HasIndex("IdFichaTecnica", "IdCausaPasos");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.TipoAccion", b =>
                {
                    b.Property<int>("IdTipoAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoAccion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoAccion");

                    b.ToTable("Tipos_Acciones", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("TesisPractica.Models.VerificacionAccion", b =>
                {
                    b.Property<int>("IdVerificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVerificacion"));

                    b.Property<bool>("EsEfectiva")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTarea")
                        .HasColumnType("int");

                    b.Property<string>("MetodoConfirmacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdVerificacion");

                    b.HasIndex("IdTarea")
                        .IsUnique();

                    b.ToTable("VerificacionAcciones", (string)null);
                });

            modelBuilder.Entity("Comentario", b =>
                {
                    b.HasOne("TesisPractica.Models.Tarea", "Tarea")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdTarea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pieza", b =>
                {
                    b.HasOne("Cliente", "Cliente")
                        .WithMany("Piezas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TesisPractica.Models.Analisis5Porque", b =>
                {
                    b.HasOne("TesisPractica.Models.CausaPaso", "CausaPaso")
                        .WithOne("Analisis5Porque")
                        .HasForeignKey("TesisPractica.Models.Analisis5Porque", "IdFichaTecnica", "IdCausa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CausaPaso");
                });

            modelBuilder.Entity("TesisPractica.Models.CausaPaso", b =>
                {
                    b.HasOne("TesisPractica.Models.Categoria5M", "Categoria5M")
                        .WithMany()
                        .HasForeignKey("IdCategoria5M")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Paso2AnalisisCausa", "Paso2")
                        .WithMany("CausasPasos")
                        .HasForeignKey("IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria5M");

                    b.Navigation("Paso2");
                });

            modelBuilder.Entity("TesisPractica.Models.Causa_NC", b =>
                {
                    b.HasOne("TesisPractica.Models.Causa", "Causa")
                        .WithMany("CausasNC")
                        .HasForeignKey("IdCausa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.NoConformidad", "NoConformidad")
                        .WithMany("CausasNC")
                        .HasForeignKey("IdNoConformidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Causa");

                    b.Navigation("NoConformidad");
                });

            modelBuilder.Entity("TesisPractica.Models.CorridaProduccion", b =>
                {
                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithOne("CorridaProduccion")
                        .HasForeignKey("TesisPractica.Models.CorridaProduccion", "IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("TesisPractica.Models.Defecto_NC", b =>
                {
                    b.HasOne("TesisPractica.Models.Defecto", "Defecto")
                        .WithMany("DefectosNC")
                        .HasForeignKey("IdDefecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.NoConformidad", "NoConformidad")
                        .WithMany("DefectosNC")
                        .HasForeignKey("IdNoConformidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defecto");

                    b.Navigation("NoConformidad");
                });

            modelBuilder.Entity("TesisPractica.Models.Equipo", b =>
                {
                    b.HasOne("TesisPractica.Models.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("IdCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("TesisPractica.Models.Equipos_Usuarios", b =>
                {
                    b.HasOne("TesisPractica.Models.Equipo", "Equipo")
                        .WithMany("EquiposUsuarios")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Usuario", "Usuario")
                        .WithMany("Equipos_Usuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisPractica.Models.FichaTecnica", b =>
                {
                    b.HasOne("TesisPractica.Models.Equipo", "Equipo")
                        .WithMany("FichasTecnicas")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TesisPractica.Models.Estado", "Estado")
                        .WithMany("FichasTecnicas")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TesisPractica.Models.NoConformidad", "NoConformidad")
                        .WithOne("FichaTecnica")
                        .HasForeignKey("TesisPractica.Models.FichaTecnica", "IdNoConformidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Estado");

                    b.Navigation("NoConformidad");
                });

            modelBuilder.Entity("TesisPractica.Models.NoConformidad", b =>
                {
                    b.HasOne("TesisPractica.Models.Detectabilidad", "Detectabilidad")
                        .WithMany("NoConformidades")
                        .HasForeignKey("IdDetectabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pieza", "Pieza")
                        .WithMany("NoConformidades")
                        .HasForeignKey("IdPieza")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Prioridad", "Prioridad")
                        .WithMany()
                        .HasForeignKey("IdPrioridad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("IdProceso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Detectabilidad");

                    b.Navigation("Estado");

                    b.Navigation("Pieza");

                    b.Navigation("Prioridad");

                    b.Navigation("Proceso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisPractica.Models.Notificacion", b =>
                {
                    b.HasOne("TesisPractica.Models.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisPractica.Models.Paso0Contencion", b =>
                {
                    b.HasOne("TesisPractica.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithOne("Paso0Contencion")
                        .HasForeignKey("TesisPractica.Models.Paso0Contencion", "IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Usuario", "ResponsableUsuario")
                        .WithMany()
                        .HasForeignKey("Responsable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("FichaTecnica");

                    b.Navigation("ResponsableUsuario");
                });

            modelBuilder.Entity("TesisPractica.Models.Paso1Verificacion", b =>
                {
                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithOne("Paso1Verificacion")
                        .HasForeignKey("TesisPractica.Models.Paso1Verificacion", "IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("TesisPractica.Models.Paso2AnalisisCausa", b =>
                {
                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithOne("Paso2AnalisisCausa")
                        .HasForeignKey("TesisPractica.Models.Paso2AnalisisCausa", "IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("TesisPractica.Models.Paso3", b =>
                {
                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithOne("Paso3")
                        .HasForeignKey("TesisPractica.Models.Paso3", "IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("TesisPractica.Models.Paso4", b =>
                {
                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithOne("Paso4")
                        .HasForeignKey("TesisPractica.Models.Paso4", "IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("TesisPractica.Models.Paso5", b =>
                {
                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithOne("Paso5")
                        .HasForeignKey("TesisPractica.Models.Paso5", "IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("TesisPractica.Models.Paso6", b =>
                {
                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithOne("Paso6")
                        .HasForeignKey("TesisPractica.Models.Paso6", "IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("TesisPractica.Models.PasswordReset", b =>
                {
                    b.HasOne("TesisPractica.Models.Usuario", "Usuario")
                        .WithMany("PasswordResets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisPractica.Models.Tarea", b =>
                {
                    b.HasOne("TesisPractica.Models.Estado", "Estado")
                        .WithMany("Tareas")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.FichaTecnica", "FichaTecnica")
                        .WithMany("Tareas")
                        .HasForeignKey("IdFichaTecnica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Prioridad", "Prioridad")
                        .WithMany("Tareas")
                        .HasForeignKey("IdPrioridad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.Usuario", "Responsable")
                        .WithMany("TareasAsignadas")
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.TipoAccion", "TipoAccion")
                        .WithMany("Tareas")
                        .HasForeignKey("IdTipoAccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisPractica.Models.CausaPaso", "CausaPaso")
                        .WithMany("Tareas")
                        .HasForeignKey("IdFichaTecnica", "IdCausaPasos")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CausaPaso");

                    b.Navigation("Estado");

                    b.Navigation("FichaTecnica");

                    b.Navigation("Prioridad");

                    b.Navigation("Responsable");

                    b.Navigation("TipoAccion");
                });

            modelBuilder.Entity("TesisPractica.Models.VerificacionAccion", b =>
                {
                    b.HasOne("TesisPractica.Models.Tarea", "Tarea")
                        .WithOne("VerificacionAccion")
                        .HasForeignKey("TesisPractica.Models.VerificacionAccion", "IdTarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("Cliente", b =>
                {
                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("Pieza", b =>
                {
                    b.Navigation("NoConformidades");
                });

            modelBuilder.Entity("TesisPractica.Models.Causa", b =>
                {
                    b.Navigation("CausasNC");
                });

            modelBuilder.Entity("TesisPractica.Models.CausaPaso", b =>
                {
                    b.Navigation("Analisis5Porque");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("TesisPractica.Models.Defecto", b =>
                {
                    b.Navigation("DefectosNC");
                });

            modelBuilder.Entity("TesisPractica.Models.Detectabilidad", b =>
                {
                    b.Navigation("NoConformidades");
                });

            modelBuilder.Entity("TesisPractica.Models.Equipo", b =>
                {
                    b.Navigation("EquiposUsuarios");

                    b.Navigation("FichasTecnicas");
                });

            modelBuilder.Entity("TesisPractica.Models.Estado", b =>
                {
                    b.Navigation("FichasTecnicas");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("TesisPractica.Models.FichaTecnica", b =>
                {
                    b.Navigation("CorridaProduccion")
                        .IsRequired();

                    b.Navigation("Paso0Contencion");

                    b.Navigation("Paso1Verificacion");

                    b.Navigation("Paso2AnalisisCausa");

                    b.Navigation("Paso3");

                    b.Navigation("Paso4");

                    b.Navigation("Paso5");

                    b.Navigation("Paso6");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("TesisPractica.Models.NoConformidad", b =>
                {
                    b.Navigation("CausasNC");

                    b.Navigation("DefectosNC");

                    b.Navigation("FichaTecnica")
                        .IsRequired();
                });

            modelBuilder.Entity("TesisPractica.Models.Paso2AnalisisCausa", b =>
                {
                    b.Navigation("CausasPasos");
                });

            modelBuilder.Entity("TesisPractica.Models.Prioridad", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("TesisPractica.Models.Tarea", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("VerificacionAccion");
                });

            modelBuilder.Entity("TesisPractica.Models.TipoAccion", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("TesisPractica.Models.Usuario", b =>
                {
                    b.Navigation("Equipos_Usuarios");

                    b.Navigation("Notificaciones");

                    b.Navigation("PasswordResets");

                    b.Navigation("TareasAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
